---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Enable Nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    use: "{{ service_bin }}"

- name: Transfer nginx conf file
  ansible.builtin.template:
    src: reverse-proxy.conf.j2
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    mode: 0600

- name: Remove default config
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: (Re)Start Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    use: "{{ service_bin }}"
